version: '3.8'

services:
  app:
    container_name: grocery-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000" 
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=grocery_db
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - grocery_network
    command: ["npm", "run", "dev"] 

  db:
    container_name: grocery-db
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: grocery_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - grocery_network

volumes:
  db_data:

networks:
  grocery_network:
    driver: bridge
